services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "nixos"
      DISK_SIZE: "32G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      # the default 2-core system from github.
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: on-failure
    stop_grace_period: 2m
